@baseUrl = http://localhost:3333

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "jeferson@email.com.br",
  "password": "uma_senha_forte123"
}

###

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jeferson Franco de Oliveira",
  "email": "jeferson1@email.com.br",
  "password": "SenhaForte123",
  "cpf": "11144477735",
  "phone": "998877666",
  "address": {
    "addressLine1": "Rua Exemplo, 123",
    "addressLine2": "Apto 101",
    "neighborhood": "Bairro Central",
    "city": "Fortaleza",
    "state": "CE",
    "postalCode": "60000000",
    "country": "Brasil"
  }
}
### 

GET {{baseUrl}}/accounts
Content-Type: application/json
