@baseUrl = http://localhost:3333
@authToken  = {{authenticate.response.body.access_token}}

# @name authenticate
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "jeferson@professional.com.br",
  "password": "SenhaForte123"
}

###

# @name forgot_password
POST {{baseUrl}}/forgot-password
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "jeferson@professional.com.br",
  "newPassword": "SenhaForte12345",
  "newPasswordConfirmation": "SenhaForte12345"
}


###

# @name create_professional_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jeferson Franco de Oliveira",
  "email": "jeferson@professional.com.br",
  "password": "SenhaForte123",
  "cpf": "71264124368",
  "role": "PROFESSIONAL",
  "phone": "9988776655",
  "address": {
    "addressLine1": "Rua Exemplo, 123",
    "addressLine2": "Apto 101",
    "neighborhood": "Bairro Central",
    "city": "Fortaleza",
    "state": "CE",
    "postalCode": "60000000",
    "country": "Brasil"
  },
  "session_price": 20
}

###

# @name create_client_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jeferson Franco de Oliveira",
  "email": "jeferson@client.com.br",
  "password": "SenhaForte123",
  "cpf": "07609254371",
  "role": "CLIENT",
  "phone": "9988776622",
  "address": {
    "addressLine1": "Rua Exemplo, 123",
    "addressLine2": "Apto 101",
    "neighborhood": "Bairro Central",
    "city": "Fortaleza",
    "state": "CE",
    "postalCode": "60000000",
    "country": "Brasil"
  }
}
### 

POST {{baseUrl}}/organization
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "John Doe`s Organization 2",
  "cnpj": "12.343.678/0001-95",
  "professionalsIds": ["a3832635-5411-4c1f-aeb6-906ee1b028d2"],
  "address": {
    "addressLine1": "Rua Exemplo, 123",
    "addressLine2": "Apto 101",
    "neighborhood": "Bairro Central",
    "city": "Fortaleza",
    "state": "CE",
    "postalCode": "60000000",
    "country": "Brasil"
  }
}

###

GET {{baseUrl}}/organizations
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET {{baseUrl}}/professionals
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET {{baseUrl}}/clients?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

POST {{baseUrl}}/schedules
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "professionalId": "80bd51eb-a225-4049-a5d0-01042834617f",
  "startDateTime": "2024-06-11T14:30:00.000Z",
  "modality": "IN_PERSON"
}